### ISSUE TITLE
What's the best way to set a bias?

### ISSUE THREAD

**Issue by jd327** [yetzt/node-geocluster#2]
Hi @yetzt,

Just a quick question -- is there any relation between bias and distance (in km or miles)? We're trying to figure out best bias to set so that we get 1 point for approximately a large city. Any recommendations you can give on how to do that besides trial and error guessing?

**Comment by yetzt** [comment]
s-means resorts to standard derivation for clustering, and the bias parameter is just a mutliplier for stddev. for your intent, another algorithm like OPTICS would probably make more sense, since it can find clusters with different densities and ignore scatter. if you want to stick to this module and s-means, you have to play aroud with the parameter a lot.

**Comment by jd327** [comment]
Thank you @yetzt, I did some quick research on OPTICS, and it looks very interesting. Glad you pointed me to it, I will experiment more with bias setting and checking out https://www.npmjs.com/package/density-clustering at the same time.

Really helpful, thanks a bunch :]
