### ISSUE TITLE
More info regarding geocluster bias

### ISSUE THREAD

**Issue by ghost** [yetzt/node-geocluster#3]
I'm using the geocluster module to some map markers in our react native app but changing the bias parameter doesn't seem to change the geocluster function output (all my points are relatively close, all within 500m). In the README its set to 1.5.  
Any hints on min/max value or anything else helpful? I'm trying to correlate the geocluster bias with what I have (latitude, longitude and deltas).

**Comment by yetzt** [comment]
the bias is not an absolute value, but a manipulator for the standard derivation of your data. there should be more clusters (because more points should be beyond the threshold for being in a new cluster, which is derived from the stddev) but it's dependent on the properties of the input. 

(i wrote this quite some
time ago and don't have the theory present, but i shall revisit k-means, s-means and clustering at some
point.)

**Comment by yetzt** [comment]
as far as i remember, all the *-means methods look for more or less equal size clusters, not density or other properties. so if this is useful to you depends on what you're trying to achieve.
